services:
  shark2mqtt:
    image: ghcr.io/camsoper/shark2mqtt:latest
    build: .
    env_file: .env
    volumes:
      - shark2mqtt_data:/data
    restart: unless-stopped

volumes:
  shark2mqtt_data:
